### ISSUE TITLE
Does also work with the Eastron modules from HomeWizard?

### ISSUE THREAD

**Issue by PvdGulik** [Eraser3/HomeWizard-Wifi-p1-plugin#2]
I have bought a Eastron SDM630-wifi via the Homewizard site. Does this plugin also work with this one?

Thanks!

**Comment by buitenb** [comment]
For the Eastron use the http poller function in domoticz . Enable the local api in the homewizzard app . 
Use this as a guide , i have the 1 phase meter .
https://www.domoticz.com/forum/viewtopic.php?p=290613#p290613

**Comment by PvdGulik** [comment]
Thanks! I'll try that in the weekend 😉

**Comment by Eraser3** [comment]
This plugin is specifically for the Wifi P1 meter. No other devices are supported.
