### ISSUE TITLE
Issue with smr_version

### ISSUE THREAD

**Issue by tgiesela** [Eraser3/HomeWizard-Wifi-p1-plugin#4]
'smr_version' is not present in the return values from my HomeWizard P1 meter. This causes the plugin to crash. It should be an optional. I have made smr_version optional and then it works.

**Comment by tgiesela** [comment]
I manually changed it to an optional parameter and then it works. It seems other people are having the same issue.

**Comment by tgiesela** [comment]
if ( 'smr_version' in Data ):
                    self.smr_version = Data['smr_version']

**Comment by Eraser3** [comment]
The HomeWizard API does not show the SMR version as an optional value, that's why I didn't check it.
I have commented out the reading of the SMR version for now because it didn't serve any purpose. Thank you for the heads up.
