### ISSUE TITLE
Failed to read response data

### ISSUE THREAD

**Issue by MikeGithub9** [Eraser3/HomeWizard-Wifi-p1-plugin#5]
Using Domoticz and you're Plugin.

After 2 weeks I'am getting this error;
 Error: P1: Failed to read response data

Could you help me? Please let me know what you need to support?
It was working great :-)

Greetings,

Mike

**Comment by maartenmolenaar** [comment]
Hallo, I have the same probleem. It started sunday morning at 6.00 CET.  Before it workshop fine.

regards, Maarten

**Comment by rleunk** [comment]
Worked good for a month, but tonight around 19:00 the same problem

**Comment by buitenb** [comment]
I also have the same problem, the data from the dongle is readable from its ip adres in json. 
And in the homewizzard ap it is working great.

**Comment by buitenb** [comment]
He guys , i updated to the latest plugin , and again not working ....
But then i looked at the code and i saw that you only need the ip adres of you dongle ! Not the full path ( ip adres/api/v1/data) 
Hope this is informative .

**Comment by Eraser3** [comment]
The latest update should have fixed this issue.
