### ISSUE TITLE
Failed to create devices

### ISSUE THREAD

**Issue by hve22** [Eraser3/HomeWizard-Wifi-p1-plugin#6]
After installling the plugin and entering the hardware configuration in domoticz NO devices are created.

![image](https://user-images.githubusercontent.com/125356950/218743830-b658baeb-30ac-402a-86e5-2a7451b2a77f.png)

**Comment by hve22** [comment]
Solved.

**Comment by Eraser3** [comment]
The devices will only be created after the data has been read. Check your Domoticz log to see if there are any errors showing.

**Comment by renedans** [comment]
Create a directory "HomeWizard-Wifi-p1-plugin" under domoticz/plugins
Place the 2 files there, reboot...done
